spring:
  data:
    mongodb:
      uri: mongodb://test:test123@localhost:27017/mons_db
      database: mons_db
      auto-index-creation: true
      host: localhost
      port: 27017
      username: test
      password: test123
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  access-key-id: test
  secret-access-key: test
  region: ap-northeast-1
  s3:
    bucket-name: bucket-s3
